### ISSUE TITLE
Replace post-title-card image to shape that I created on flutter

### ISSUE THREAD

**Issue by aoiorio** [aoiorio/Travel-Knock#47]
## 🍤Description
This issue is about replacing post-title-card image to shape that I created on flutter.
And I'd like to support responsive of  thumbnail's shape at PlanDetailsPage
## 🥟Links
[convert SVG to custom shape on web](https://itchylabs.com/tools/path-to-bezier/)
[Youtube convert SVG to custom shape on web](https://www.youtube.com/watch?v=P0eZ0XH5FdI)

## 🍿TODO
- [x] convert SVG to custom shape
- [x] support responsive of post-title-card
- [x] support responsive of thumbnail's shape at PlanDetailsPage

**Comment by aoiorio** [comment]
![LGTM](https://image.lgtmoon.dev/226032)
